"""
Economic Calendar Module - Deterministic, DST-aware event schedule.

Generates high-impact economic event dates for prompt injection so the
decision LLMs know exactly when high-volatility events occur (no more
vague 'NFP risk' HOLDs).

Design:
- Recurring events (NFP, CPI, PCE, GDP, Retail Sales) are generated by rule
  (e.g. NFP = first Friday of the month) in WIB with US DST awareness.
- Non-recurring / precisely-scheduled events (FOMC, ECB, BOE, BOJ, SNB)
  are provided via a manual OVERRIDE list (verified against official sources).
- The module injects a short text block into the prompt with the nearest
  upcoming events (next 48h / this week).
"""

from datetime import datetime, timedelta, date
from zoneinfo import ZoneInfo
import calendar as cal

WIB = ZoneInfo("Asia/Jakarta")

# ============================================================================
#  US DST: second Sunday of March -> first Sunday of November
# ============================================================================
def us_dst_active(d: date) -> bool:
    """True if US Daylight Saving Time is active on date d (local US)."""
    # DST starts 2nd Sunday of March (02:00 local), ends 1st Sunday of November
    march = date(d.year, 3, 1)
    second_sunday = march + timedelta(days=(6 - march.weekday()) % 7 + 7)
    november = date(d.year, 11, 1)
    first_sunday = november + timedelta(days=(6 - november.weekday()) % 7)
    return second_sunday <= d < first_sunday


def us_release_wib(release_date: date, release_et_hour: int = 8, release_et_min: int = 30) -> datetime:
    """
    Convert a US Eastern Time release time to WIB.
    Standard time: ET = UTC-5, WIB = UTC+7 -> +12h
    DST:           ET = UTC-4, WIB = UTC+7 -> +11h
    """
    offset = 11 if us_dst_active(release_date) else 12
    return datetime(release_date.year, release_date.month, release_date.day,
                    release_et_hour, release_et_min, tzinfo=WIB) + timedelta(hours=offset)


def first_friday(year: int, month: int) -> date:
    d = date(year, month, 1)
    days_ahead = (4 - d.weekday()) % 7
    return d + timedelta(days=days_ahead)


def _generate_recurring(year: int) -> list[dict]:
    """Recurring US high-impact events (rule-based)."""
    events = []
    for month in range(1, 13):
        # NFP + Unemployment: first Friday, 8:30 ET
        nfp_day = first_friday(year, month)
        nfp_dt = us_release_wib(nfp_day)
        events.append({"name": "US Non-Farm Payrolls (NFP) + Unemployment Rate",
                       "dt": nfp_dt, "impact": "HIGH"})
        # CPI: mid-month (~12th), 8:30 ET
        cpi_day = date(year, month, 12)
        events.append({"name": "US CPI (Inflation)", "dt": us_release_wib(cpi_day), "impact": "HIGH"})
        # Retail Sales: mid-month (~14th)
        rs_day = date(year, month, 14)
        events.append({"name": "US Retail Sales", "dt": us_release_wib(rs_day), "impact": "HIGH"})
        # PCE: end of month (~26th)
        pce_day = date(year, month, 26)
        events.append({"name": "US PCE (Fed's preferred inflation)", "dt": us_release_wib(pce_day), "impact": "HIGH"})
    # GDP: quarterly, end of quarter months (Jan/Apr/Jul/Oct = ~26th)
    for month in [1, 4, 7, 10]:
        gdp_day = date(year, month, 26)
        events.append({"name": "US GDP (quarterly)", "dt": us_release_wib(gdp_day), "impact": "HIGH"})
    return events


# ============================================================================
#  OVERRIDE: precisely-scheduled, non-recurring events (verified sources)
#  Times in WIB. 2026 dates from official calendars (Fed, ECB, BOE, BOJ).
# ============================================================================
# NOTE: 2026 dates. To keep this accurate, review this list when the year changes.
OVERRIDES: list[dict] = [
    # FOMC 2026 (decision day, 2:00 PM ET -> WIB)
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 1, 28, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 3, 18, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 4, 29, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 6, 17, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 7, 29, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 9, 16, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 10, 28, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 12, 9, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    # ECB: decision Thursdays 14:15 CET/CEST -> WIB (DST summer +5, winter +6)
    {"name": "ECB Rate Decision", "dt": datetime(2026, 9, 10, 19, 15, tzinfo=WIB), "impact": "HIGH"},
    # BOE: 12:00 London -> WIB (BST +7, GMT +8)
    {"name": "BOE Rate Decision", "dt": datetime(2026, 9, 17, 18, 0, tzinfo=WIB), "impact": "HIGH"},
    # BOJ: policy statement ~midday JST -> WIB (JST = UTC+9, WIB = UTC+7)
    {"name": "BOJ Rate Decision", "dt": datetime(2026, 9, 18, 10, 0, tzinfo=WIB), "impact": "HIGH"},
    # SNB: quarterly (March/June/Sept/Dec), 09:30 CET -> WIB
    {"name": "SNB Rate Decision", "dt": datetime(2026, 9, 24, 15, 30, tzinfo=WIB), "impact": "HIGH"},
    # China: NBS releases ~9th-10th (CPI/PPI) and ~15th (retail/IP/FAI), 10:00 Beijing -> WIB (same)
    {"name": "China CPI/PPI", "dt": datetime(2026, 9, 10, 10, 0, tzinfo=WIB), "impact": "MEDIUM"},
    {"name": "China GDP (Q3)", "dt": datetime(2026, 10, 19, 10, 0, tzinfo=WIB), "impact": "HIGH"},
]


class EconomicCalendar:
    """Builds and queries the event schedule for prompt injection."""

    # Only inject events within this many hours ahead (token saving).
    # 3h gives a short head-start before the 15-30min caution window without
    # spamming the prompt on every 5-minute candle during quiet days.
    EVENT_WINDOW_HOURS = 3

    def __init__(self):
        self._events = []
        # Generate current + next year so the schedule always covers ahead
        this_year = datetime.now(WIB).year
        for y in [this_year, this_year + 1]:
            self._events.extend(_generate_recurring(y))
        self._events.extend(OVERRIDES)
        self._events.sort(key=lambda e: e["dt"])

    def get_upcoming(self, now=None, hours_ahead: int = 48) -> list[dict]:
        """Returns upcoming events within the next N hours, sorted by time."""
        now = now or datetime.now(WIB)
        horizon = now + timedelta(hours=hours_ahead)
        return [e for e in self._events if now <= e["dt"] <= horizon]

    def get_context(self, now=None) -> str:
        """
        Returns a compact markdown block for prompt injection, but ONLY when
        a high-impact event is imminent (within EVENT_WINDOW_HOURS).
        Returns "" (empty) otherwise - saves tokens on quiet candles and
        avoids injecting far-future events the LLM doesn't need to act on.
        """
        now = now or datetime.now(WIB)
        upcoming = self.get_upcoming(now, hours_ahead=self.EVENT_WINDOW_HOURS)
        if not upcoming:
            return ""
        lines = [f"### UPCOMING HIGH-IMPACT ECONOMIC EVENTS (next {self.EVENT_WINDOW_HOURS}h)"]
        for e in upcoming[:4]:
            delta = e["dt"] - now
            hours = delta.total_seconds() / 3600
            lines.append(f"- {e['name']} in {hours:.1f}h ({e['dt'].strftime('%a %d %b %H:%M WIB')}) [{e['impact']}]")
        return "\n".join(lines) + "\n"


# Singleton instance
calendar = EconomicCalendar()
