"""
Economic Calendar Module - Deterministic, DST-aware event schedule.

Generates high-impact economic event dates for prompt injection so the
decision LLMs know exactly when high-volatility events occur (no more
vague 'NFP risk' HOLDs).

Design:
- Recurring events (NFP, CPI, PCE, GDP, Retail Sales) are generated by rule
  (e.g. NFP = first Friday of the month) in WIB with US DST awareness.
- Non-recurring / precisely-scheduled events (FOMC, ECB, BOE, BOJ, SNB)
  are provided via a manual OVERRIDE list (verified against official sources).
- The module injects a short text block into the prompt with the nearest
  upcoming events (next 48h / this week).
"""

from datetime import datetime, timedelta, date
from zoneinfo import ZoneInfo
import calendar as cal
import json
import os
import urllib.request
import urllib.parse

WIB = ZoneInfo("Asia/Jakarta")

# ============================================================================
#  US DST: second Sunday of March -> first Sunday of November
# ============================================================================
def us_dst_active(d: date) -> bool:
    """True if US Daylight Saving Time is active on date d (local US)."""
    # DST starts 2nd Sunday of March (02:00 local), ends 1st Sunday of November
    march = date(d.year, 3, 1)
    second_sunday = march + timedelta(days=(6 - march.weekday()) % 7 + 7)
    november = date(d.year, 11, 1)
    first_sunday = november + timedelta(days=(6 - november.weekday()) % 7)
    return second_sunday <= d < first_sunday


def us_release_wib(release_date: date, release_et_hour: int = 8, release_et_min: int = 30) -> datetime:
    """
    Convert a US Eastern Time release time to WIB.
    Standard time: ET = UTC-5, WIB = UTC+7 -> +12h
    DST:           ET = UTC-4, WIB = UTC+7 -> +11h
    """
    offset = 11 if us_dst_active(release_date) else 12
    return datetime(release_date.year, release_date.month, release_date.day,
                    release_et_hour, release_et_min, tzinfo=WIB) + timedelta(hours=offset)


def first_friday(year: int, month: int) -> date:
    d = date(year, month, 1)
    days_ahead = (4 - d.weekday()) % 7
    return d + timedelta(days=days_ahead)


def _generate_recurring(year: int) -> list[dict]:
    """Recurring US high-impact events (rule-based)."""
    events = []
    for month in range(1, 13):
        # NFP + Unemployment: first Friday, 8:30 ET
        nfp_day = first_friday(year, month)
        nfp_dt = us_release_wib(nfp_day)
        events.append({"name": "US Non-Farm Payrolls (NFP) + Unemployment Rate",
                       "dt": nfp_dt, "impact": "HIGH"})
        # CPI: mid-month (~12th), 8:30 ET
        cpi_day = date(year, month, 12)
        events.append({"name": "US CPI (Inflation)", "dt": us_release_wib(cpi_day), "impact": "HIGH"})
        # Retail Sales: mid-month (~14th)
        rs_day = date(year, month, 14)
        events.append({"name": "US Retail Sales", "dt": us_release_wib(rs_day), "impact": "HIGH"})
        # PCE: end of month (~26th)
        pce_day = date(year, month, 26)
        events.append({"name": "US PCE (Fed's preferred inflation)", "dt": us_release_wib(pce_day), "impact": "HIGH"})
    # GDP: quarterly, end of quarter months (Jan/Apr/Jul/Oct = ~26th)
    for month in [1, 4, 7, 10]:
        gdp_day = date(year, month, 26)
        events.append({"name": "US GDP (quarterly)", "dt": us_release_wib(gdp_day), "impact": "HIGH"})
    return events


# ============================================================================
#  OVERRIDE: precisely-scheduled, non-recurring events (verified sources)
#  Times in WIB. 2026 dates from official calendars (Fed, ECB, BOE, BOJ).
# ============================================================================
# NOTE: 2026 dates. To keep this accurate, review this list when the year changes.
OVERRIDES: list[dict] = [
    # FOMC 2026 (decision day, 2:00 PM ET -> WIB)
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 1, 28, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 3, 18, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 4, 29, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 6, 17, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 7, 29, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 9, 16, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 10, 28, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    {"name": "FOMC Rate Decision", "dt": datetime(2026, 12, 9, 2, 0, tzinfo=WIB), "impact": "HIGH"},
    # FOMC Minutes 2026: released ~3 weeks after each meeting at 14:00 ET.
    # 14:00 ET -> WIB: DST active = +11h (01:00 WIB next day), standard = +12h
    # (02:00 WIB next day). Uses us_release_wib() for exact DST-aware conversion.
    # Meeting 29 Jul -> Minutes released 19 Aug 2026 (14:00 ET = 01:00 WIB Aug 20)
    # = the FOMC Minutes night that caused the 19 Aug CHF crash (6 BUY losses).
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 2, 18), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 4, 8), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 5, 20), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 7, 8), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 8, 19), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 10, 7), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 11, 18), 14, 0), "impact": "HIGH"},
    {"name": "FOMC Minutes", "dt": us_release_wib(date(2026, 12, 30), 14, 0), "impact": "HIGH"},
    # ECB: decision Thursdays 14:15 CET/CEST -> WIB (DST summer +5, winter +6)
    {"name": "ECB Rate Decision", "dt": datetime(2026, 9, 10, 19, 15, tzinfo=WIB), "impact": "HIGH"},
    # BOE: 12:00 London -> WIB (BST +7, GMT +8)
    {"name": "BOE Rate Decision", "dt": datetime(2026, 9, 17, 18, 0, tzinfo=WIB), "impact": "HIGH"},
    # BOJ: policy statement ~midday JST -> WIB (JST = UTC+9, WIB = UTC+7)
    {"name": "BOJ Rate Decision", "dt": datetime(2026, 9, 18, 10, 0, tzinfo=WIB), "impact": "HIGH"},
    # SNB: quarterly (March/June/Sept/Dec), 09:30 CET -> WIB
    {"name": "SNB Rate Decision", "dt": datetime(2026, 9, 24, 15, 30, tzinfo=WIB), "impact": "HIGH"},
    # China: NBS releases ~9th-10th (CPI/PPI) and ~15th (retail/IP/FAI), 10:00 Beijing -> WIB (same)
    {"name": "China CPI/PPI", "dt": datetime(2026, 9, 10, 10, 0, tzinfo=WIB), "impact": "MEDIUM"},
    {"name": "China GDP (Q3)", "dt": datetime(2026, 10, 19, 10, 0, tzinfo=WIB), "impact": "HIGH"},
]


class EconomicCalendar:
    """Builds and queries the event schedule for prompt injection."""

    # Inject events within this window (token saving + news-awareness).
    # EVENT_BEFORE_HOURS: how far ahead to warn about imminent events.
    # EVENT_AFTER_HOURS : how far back to flag recently-released events
    #   (post-news volatility can persist; the LLM must not fade it).
    # 6h both ways covers the FOMC Minutes case (14:00 ET = 01:00 WIB next day):
    #   warning appears from ~19:00 WIB the prior evening until 07:00 WIB.
    EVENT_BEFORE_HOURS = 6
    EVENT_AFTER_HOURS = 6

    # =========================================================================
    #  Dual-Source Dynamic Fetch:
    #  1. PRIMARY : ForexFactory Official JSON Feed (Fastly CDN, highly accurate FX impact & Bank Holidays)
    #  2. FALLBACK: TradingView Economic Calendar API
    # =========================================================================
    FETCH_FOREXFACTORY_URL = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
    FETCH_TRADINGVIEW_URL  = "https://economic-calendar.tradingview.com/events"
    FETCH_CACHE_FILE       = os.path.join("data", "economic_events_cache.json")
    FETCH_LOOKBACK_HOURS   = 12
    FETCH_LOOKAHEAD_HOURS  = 48
    FETCH_IMPORTANCE_MIN   = 1

    FETCH_KEYWORDS = (
        "FOMC", "CPI", "NFP", "Non Farm", "Payroll", "Payrolls",
        "Minutes", "Rate Decision", "PMI", "GDP", "PCE", "Retail Sales",
        "Unemployment", "Employment", "Inflation", "Revision", "Benchmark",
        "Fed", "Powell", "Warsh", "Speaks", "Speech", "Chairman", "Governor",
        "Press Conference", "Testimony", "Interest Rate", "Official Cash Rate",
        "Overnight Rate", "Monetary Policy", "Bank Holiday", "Holiday"
    )

    COUNTRY_CURRENCY = {
        "US": "USD", "GB": "GBP", "EU": "EUR", "JP": "JPY",
        "AU": "AUD", "CA": "CAD", "CH": "CHF", "NZ": "NZD", "CN": "CNY",
        "USD": "USD", "GBP": "GBP", "EUR": "EUR", "JPY": "JPY",
        "AUD": "AUD", "CAD": "CAD", "CHF": "CHF", "NZD": "NZD", "CNY": "CNY",
    }

    _HEADERS_FF = {
        "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"),
        "Accept": "application/json",
    }

    _HEADERS_TV = {
        "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"),
        "Accept": "application/json",
        "Origin": "https://www.tradingview.com",
        "Referer": "https://www.tradingview.com/",
    }

    # -------------------------------------------------------------------------
    #  Resolve config (lazy import biar tidak circular: economic_calendar <- config)
    # -------------------------------------------------------------------------
    def _cfg(self):
        try:
            from config import (ECONOMIC_NEWS_ENABLED, ECONOMIC_NEWS_TTL_HOURS,
                                ECONOMIC_NEWS_COUNTRIES, ECONOMIC_NEWS_GLOBAL_KEYWORDS)
            return (ECONOMIC_NEWS_ENABLED, ECONOMIC_NEWS_TTL_HOURS,
                    ECONOMIC_NEWS_COUNTRIES, ECONOMIC_NEWS_GLOBAL_KEYWORDS)
        except Exception:
            return (True, 6, ["US", "GB", "EU", "CH", "JP", "AU", "CA", "NZ", "USD", "GBP", "EUR", "CHF", "JPY", "AUD", "CAD", "NZD"], ())

    @staticmethod
    def _symbol_currencies(symbol: str) -> set:
        """Extract base/quote currencies from a symbol like 'GBPUSD-ECNc' -> {GBP, USD}."""
        sym = (symbol or "").upper()
        body = sym.split("-")[0].split(".")[0]
        if len(body) == 6 and body[:3] in {"GBP", "USD", "EUR", "JPY", "AUD", "CAD", "CHF", "NZD"} \
                and body[3:] in {"GBP", "USD", "EUR", "JPY", "AUD", "CAD", "CHF", "NZD"}:
            return {body[:3], body[3:]}
        return set()

    def _event_matches_symbol(self, event: dict, symbol: str) -> bool:
        """
        Per-pair relevance filter:
        - Event GLOBAL (FOMC/NFP/Powell/Trump speech/Fed Chair) -> semua symbol.
        - Event negara lain -> hanya symbol yang mengandung mata uang negara tsb.
        - Non-FX (XAU/BTC) -> hanya event USD/Global.
        - China (CNY) -> AUD dan NZD.
        """
        _, _, countries, global_keywords = self._cfg()
        title = event.get("name", "")
        country = event.get("country", "")
        currency = event.get("currency") or self.COUNTRY_CURRENCY.get(country)

        # Global US event
        if (country in ("US", "USD")) and any(k.lower() in title.lower() for k in global_keywords):
            return True

        if not currency:
            return False

        sym_ccys = self._symbol_currencies(symbol)
        if not sym_ccys:
            return currency == "USD"

        # China events affect AUD and NZD
        if currency == "CNY" and any(c in sym_ccys for c in ("AUD", "NZD")):
            return True

        return currency in sym_ccys

    def _is_relevant_country(self, country: str) -> bool:
        """Whitelist check."""
        _, _, countries, _ = self._cfg()
        c_upper = (country or "").upper()
        return c_upper in countries or self.COUNTRY_CURRENCY.get(c_upper) in countries

    def __init__(self):
        self._events = []
        this_year = datetime.now(WIB).year
        for y in [this_year, this_year + 1]:
            self._events.extend(_generate_recurring(y))
        self._events.extend(OVERRIDES)
        self._events.sort(key=lambda e: e["dt"])
        self._dynamic_events = []
        self._fetched_at = 0.0
        self._load_cache()

    def _load_cache(self):
        """Load previously fetched events from disk (best-effort)."""
        try:
            if os.path.exists(self.FETCH_CACHE_FILE):
                with open(self.FETCH_CACHE_FILE, "r", encoding="utf-8") as f:
                    data = json.load(f)
                self._fetched_at = float(data.get("fetched_at", 0.0))
                events = []
                for e in data.get("events", []):
                    try:
                        events.append({
                            "name": e["name"],
                            "dt": datetime.fromisoformat(e["dt"]),
                            "impact": e.get("impact", "HIGH"),
                            "country": e.get("country", ""),
                            "currency": e.get("currency", self.COUNTRY_CURRENCY.get(e.get("country", ""), "")),
                            "forecast": e.get("forecast"),
                            "previous": e.get("previous"),
                            "actual": e.get("actual")
                        })
                    except Exception:
                        continue
                self._dynamic_events = events
        except Exception:
            self._dynamic_events = []
            self._fetched_at = 0.0

    def _save_cache(self, source: str = "forexfactory"):
        """Persist fetched events to disk (best-effort)."""
        try:
            os.makedirs(os.path.dirname(self.FETCH_CACHE_FILE), exist_ok=True)
            with open(self.FETCH_CACHE_FILE, "w", encoding="utf-8") as f:
                json.dump({
                    "fetched_at": self._fetched_at,
                    "source": source,
                    "events": [
                        {
                            "name": e["name"],
                            "dt": e["dt"].isoformat(),
                            "impact": e["impact"],
                            "country": e.get("country", ""),
                            "currency": e.get("currency", ""),
                            "forecast": e.get("forecast"),
                            "previous": e.get("previous"),
                            "actual": e.get("actual")
                        }
                        for e in self._dynamic_events
                    ],
                }, f, indent=2)
        except Exception:
            pass

    def _fetch_forexfactory(self, now: datetime) -> list[dict]:
        """
        Primary Provider: Fetch live weekly calendar from ForexFactory JSON API.
        Accurate folder impacts (High, Medium, Low, Holiday).
        """
        import ssl
        req = urllib.request.Request(self.FETCH_FOREXFACTORY_URL, headers=self._HEADERS_FF)
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        with urllib.request.urlopen(req, context=ctx, timeout=8) as resp:
            raw = json.loads(resp.read().decode("utf-8"))

        events = []
        lookback = now - timedelta(hours=self.FETCH_LOOKBACK_HOURS)
        lookahead = now + timedelta(hours=self.FETCH_LOOKAHEAD_HOURS)

        for e in raw:
            try:
                title = (e.get("title") or "").strip()
                ccy = (e.get("country") or "").upper().strip()
                raw_date = e.get("date") or ""
                imp_str = (e.get("impact") or "").strip()

                if not raw_date or not title:
                    continue

                dt_obj = datetime.fromisoformat(raw_date)
                dt_wib = dt_obj.astimezone(WIB)

                if not (lookback <= dt_wib <= lookahead):
                    continue

                if imp_str == "High":
                    impact = "HIGH"
                elif imp_str == "Medium":
                    impact = "MEDIUM"
                elif imp_str in ("Holiday", "Non-Economic") or "holiday" in title.lower():
                    impact = "HOLIDAY"
                elif any(k.lower() in title.lower() for k in self.FETCH_KEYWORDS):
                    impact = "MEDIUM"
                else:
                    impact = "LOW"

                if impact in ("HIGH", "MEDIUM", "HOLIDAY"):
                    events.append({
                        "name": title,
                        "dt": dt_wib,
                        "impact": impact,
                        "country": ccy,
                        "currency": ccy,
                        "forecast": e.get("forecast"),
                        "previous": e.get("previous"),
                        "actual": e.get("actual")
                    })
            except Exception:
                continue

        seen = set()
        unique = []
        for e in sorted(events, key=lambda x: x["dt"]):
            key = (e["name"], e["dt"].isoformat())
            if key not in seen:
                seen.add(key)
                unique.append(e)
        return unique

    def _fetch_tradingview(self, now: datetime) -> list[dict]:
        """
        Secondary Fallback Provider: Fetch high-impact events from TradingView economic calendar API.
        """
        import ssl
        _, _, countries, _ = self._cfg()
        frm = (now - timedelta(hours=self.FETCH_LOOKBACK_HOURS)).strftime("%Y-%m-%d")
        to = (now + timedelta(hours=self.FETCH_LOOKAHEAD_HOURS)).strftime("%Y-%m-%d")
        url = f"{self.FETCH_TRADINGVIEW_URL}?{urllib.parse.urlencode({'from': frm, 'to': to})}"
        req = urllib.request.Request(url, headers=self._HEADERS_TV)
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        with urllib.request.urlopen(req, context=ctx, timeout=10) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
        raw = payload.get("result", []) if isinstance(payload, dict) else []
        events = []
        for e in raw:
            try:
                imp = e.get("importance")
                try:
                    imp_n = int(imp)
                except (TypeError, ValueError):
                    imp_n = 0
                country = (e.get("country") or "").upper()
                title = e.get("title") or ""
                if not self._is_relevant_country(country):
                    continue
                if imp_n < self.FETCH_IMPORTANCE_MIN and not any(
                        k.lower() in title.lower() for k in self.FETCH_KEYWORDS):
                    continue
                dt_utc = datetime.fromisoformat(e["date"].replace("Z", "+00:00"))
                dt_wib = dt_utc.astimezone(WIB)
                events.append({
                    "name": title,
                    "dt": dt_wib,
                    "impact": "HIGH" if imp_n >= 1 else "MEDIUM",
                    "country": country,
                    "currency": self.COUNTRY_CURRENCY.get(country, country),
                    "forecast": e.get("forecast"),
                    "previous": e.get("previous"),
                    "actual": e.get("actual")
                })
            except Exception:
                continue
        seen = set()
        unique = []
        for e in sorted(events, key=lambda x: x["dt"]):
            key = (e["name"], e["dt"].isoformat())
            if key not in seen:
                seen.add(key)
                unique.append(e)
        return unique

    def get_events(self, now: datetime = None, symbol: str = None) -> list[dict]:
        """
        Best source of events: cache fresh (<6h) -> ForexFactory (Primary) ->
        TradingView (Fallback) -> Cache lama -> Jadwal statis OVERRIDES/recurring.
        """
        now = now or datetime.now(WIB)
        enabled, ttl_hours, _, _ = self._cfg()
        if enabled:
            if (now.timestamp() - self._fetched_at) < ttl_hours * 3600 and self._dynamic_events:
                events = self._dynamic_events
            else:
                fetched = []
                source_used = "forexfactory"
                try:
                    fetched = self._fetch_forexfactory(now)
                except Exception:
                    fetched = []

                if not fetched:
                    try:
                        fetched = self._fetch_tradingview(now)
                        source_used = "tradingview"
                    except Exception:
                        fetched = []

                if fetched:
                    self._dynamic_events = fetched
                    self._fetched_at = now.timestamp()
                    self._save_cache(source=source_used)
                    events = fetched
                elif self._dynamic_events:
                    events = self._dynamic_events
                else:
                    events = self._events
        else:
            events = self._events

        if symbol:
            events = [e for e in events if self._event_matches_symbol(e, symbol)]
        return events

    def get_upcoming(self, now=None, hours_ahead: int = 48, symbol: str = None) -> list[dict]:
        """Returns upcoming events within the next N hours, sorted by time."""
        now = now or datetime.now(WIB)
        horizon = now + timedelta(hours=hours_ahead)
        return [e for e in self.get_events(now, symbol=symbol) if now <= e["dt"] <= horizon]

    def get_context(self, now=None, symbol: str = None) -> str:
        """
        Returns a compact markdown block for prompt injection, including upcoming,
        recent, and active Bank Holidays.
        """
        now = now or datetime.now(WIB)
        events = self.get_events(now, symbol=symbol)

        today_date = now.date()
        active_holidays = [
            e for e in events
            if e.get("impact") == "HOLIDAY" and e["dt"].date() == today_date
        ]

        upcoming = [
            e for e in events
            if e.get("impact") != "HOLIDAY" and now <= e["dt"] <= now + timedelta(hours=self.EVENT_BEFORE_HOURS)
        ]
        recent = [
            e for e in events
            if e.get("impact") != "HOLIDAY" and now - timedelta(hours=self.EVENT_AFTER_HOURS) <= e["dt"] < now
        ]

        if not upcoming and not recent and not active_holidays:
            return ""

        lines = []
        if active_holidays:
            holidays_str = ", ".join([f"[{h.get('country')}] {h['name']}" for h in active_holidays])
            lines.append(f"### 🏖️ BANK HOLIDAY ALERT: {holidays_str} today -- expect thin liquidity & wider spreads")

        if upcoming:
            lines.append(f"### UPCOMING HIGH-IMPACT ECONOMIC EVENTS (next {self.EVENT_BEFORE_HOURS}h)")
            for e in upcoming[:4]:
                delta = e["dt"] - now
                hours = delta.total_seconds() / 3600
                country = (e.get("country") or "").strip()
                prefix = f"[{country}] " if country else ""
                lines.append(f"- {prefix}{e['name']} in {hours:.1f}h ({e['dt'].strftime('%a %d %b %H:%M WIB')}) [{e['impact']}]")

        if recent:
            lines.append(f"### RECENTLY RELEASED HIGH-IMPACT EVENTS (last {self.EVENT_AFTER_HOURS}h) -- volatility may persist, do not fade the move")
            for e in recent[:4]:
                delta = now - e["dt"]
                hours = delta.total_seconds() / 3600
                country = (e.get("country") or "").strip()
                prefix = f"[{country}] " if country else ""
                lines.append(f"- {prefix}{e['name']} {hours:.1f}h ago ({e['dt'].strftime('%a %d %b %H:%M WIB')}) [{e['impact']}]")

        return "\n".join(lines) + "\n"

    def is_high_impact_imminent(self, symbol: str = None, window_minutes: int = 30) -> tuple[bool, str]:
        """
        Returns (True, event_description) if there is an active high-impact event
        within the next `window_minutes` or released within the last 10 minutes.
        """
        now = datetime.now(WIB)
        events = self.get_events(now, symbol=symbol)
        for e in events:
            if e.get("impact") not in ("HIGH", "CRITICAL"):
                continue
            event_dt = e["dt"]
            diff_sec = (event_dt - now).total_seconds()
            # 1. Upcoming within window_minutes
            if 0 <= diff_sec <= (window_minutes * 60):
                mins = int(diff_sec / 60)
                return True, f"{e.get('name')} in {mins}m [{e.get('country', '')}]"
            # 2. Released very recently (< 10m ago) during violent post-news spike
            elif -(10 * 60) <= diff_sec < 0:
                mins = int(abs(diff_sec) / 60)
                return True, f"{e.get('name')} released {mins}m ago [{e.get('country', '')}]"
        return False, ""


# Singleton instance
calendar = EconomicCalendar()

